### ISSUE TITLE
OS X Bioconda package requires unnecessary llvm dependencies

### ISSUE THREAD

**Issue by karel-brinda** [kowallus/mbgc#15]
One little issue I've noticed with the OS X Bioconda packages: it installs also 
```
+ libcxx        16.0.6  hd57cbcb_0  conda-forge     Cached
+ llvm-openmp   17.0.6  hb6ac08f_0  conda-forge     Cached
```
I believe these two should be dependencies only for the build, but not for final bioconda package.

**Comment by kowallus** [comment]
_llvm-openmp_ is a required dynamic library. The _libcxx_ isn't explicitly stated in bioconda recipe.
