### ISSUE TITLE
Multiple patterns, patterns file [suggestion]

### ISSUE THREAD

**Issue by jsgounot** [kowallus/mbgc#2]
Hi,

Is it possible with the current version to provide multiple patterns during the decompression step? In some cases, I need to uncompress hundred of strains from the same large archive. I can't practically multi-process all the extraction individually with the current method, since this leads to loading the archive in memory for each process. If this is not an option, I would like to make another suggestion, that is allow to provide a file in the decompression command line, that would contain a list of patterns.

Thanks!

**Comment by kowallus** [comment]
Hi,
I agree with your assessment. Actually, after your #1 issue, I have already thought about such a feature :). It might take a while until the next release, so please be patient.

**Comment by kowallus** [comment]
The feature has been added in the new release.

**Comment by jsgounot** [comment]
That's great thanks!
