### ISSUE TITLE
Is the order of input files respected?

### ISSUE THREAD

**Issue by karel-brinda** [kowallus/mbgc#4]
Hello, would it be possible to add the info into the documentation on whether files are compressed exactly in the order in which they appear in the input (in cases such as `./mbgc c seqlist.txt comp.mbgc`)? This is info is critically important for the applications of MBGC in use cases such as phylogenetic compression (https://www.biorxiv.org/content/10.1101/2023.04.15.536996).

**Comment by karel-brinda** [comment]
We are actually very well aware of the impact of the order in LZ-based methods on the resulting compression and that's one of the reasons we introduced phylogenetic compression (see the [manuscript](https://www.biorxiv.org/content/10.1101/2023.04.15.536996) and especially the supplementary).

Phylogenetic compression actually makes MBGC extremely powerful (it can be used essentially as a pre-compression booster) and scalable to datasets of essentially any size and diversity. For instance, the 661k collection was compressed to only 20 GB (xz was slightly worse, mostly for the lack of support for reverse complements).

As we were not aware if the user-specified order is really respected, in the paper, we compressed a whole stream as a single FASTA.

(Btw. Big congrats for developing this!!)

**Comment by kowallus** [comment]
Yes, I am familiar with your research. It is great that you have included MBGC. 
I can spoiler that now MBGC2 achieves <19GB in max mode, for the whole 661k collection. I am confident that phylogenetic approach would boost the result. I have observed such phenomena on a large S.enterica cluster where MBGC2 obtains >8000x compression ratio, whereas random larger collections of that pathogen often do not reach 1000x. I will close this issue after an update in the next release.

**Comment by karel-brinda** [comment]
Fixed by https://github.com/kowallus/mbgc/commit/46d8c6b08507272a2eb2b551c0b16c0caed2fe90
